add CI

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -1,5 +1,4 @@
-# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
-# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+# Workflow for R-CMD-check with Homebrew adjustments
 on:
   push:
     branches: [main, master]
@@ -32,20 +31,28 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Update Homebrew and Remove qpdf Requirement (macOS only)
+      - name: Update Homebrew
         if: runner.os == 'macOS'
         run: |
-          brew update --auto-update
-          brew install qpdf || true
+          brew update
+
+      - name: Install qpdf
+        if: runner.os == 'macOS'
+        run: |
+          brew install qpdf || echo "qpdf installation skipped or failed gracefully."
+
+      - name: Debug Homebrew (macOS)
+        if: runner.os == 'macOS'
+        run: |
+          brew doctor
+          brew info qpdf
 
       - uses: r-lib/actions/setup-pandoc@v2
 
       - uses: r-lib/actions/setup-r@v2
         with:
           r-version: ${{ matrix.config.r }}
-          http-user-agent: ${{ matrix.config.http-user-agent }}
           use-public-rspm: true
-          install-r: true
 
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
